### ISSUE TITLE
Upvote should be executed only once per user

### ISSUE THREAD

**Issue by richeshgupta** [richeshgupta/JUETNoticeBoard#11]
Upvote & downvote should be executed only once per user

**Comment by satyam260** [comment]
This can be overcome by assigning a single button for Upvote. When  the upvote button is clicked it changes to Downvote button and this can be executed more easily.

**Comment by richeshgupta** [comment]
The problem will still exist if don't have the list saved at our models that who have voted.
We'll have a table of users who have already voted for the answer and with that information we can implement every possibility on upvotes.
What i afraid is that it will increase database requests significantly and page loading time plus if we'll host the website on a VPS it will also cost us extra. So we have to think efficiently here.
